//
// Created by kamil on 16.05.2024.
//

#ifndef INC_24L_PROI_PROJECT_2_DSOUZA_DAMIAN_MARSZALEK_KAMIL_SUSKI_MICHAL_CARD_H
#define INC_24L_PROI_PROJECT_2_DSOUZA_DAMIAN_MARSZALEK_KAMIL_SUSKI_MICHAL_CARD_H


class Card {

};


#endif //INC_24L_PROI_PROJECT_2_DSOUZA_DAMIAN_MARSZALEK_KAMIL_SUSKI_MICHAL_CARD_H
